services:
  app:
    image: blog-front-dev
    volumes:
      - ./frontend/:/usr/src/app/frontend
    container_name: blog-front-dev
  server:
    image: blog-back-dev
    volumes:
      - ./backend/:/user/src/app/backend
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app