name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: BACKEND install dependencies / check style / tests
        env:
              TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
              SECRET: ${{ secrets.SECRET }}
        run: npm install && npm run eslint && npm run test
        working-directory: backend
      - name: FRONTEND install dependencies / check style / tests
        run: npm install && npm run eslint && npm run test
        working-directory: frontend
      - name: Install dependencies for E2E-Playwright
        run: npm install
        working-directory: playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: backend
      - name: E2E test with playwright
        run: npm run test:e2e
        working-directory: backend
      
      
